spring:
  security:
    oauth2:
      client:
        registration:
          hubspot:
            client-id: CLIENT_ID
            client-secret: CLIENT_SECRET
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/oauth/callback"
            scope:
              - crm.objects.contacts.read
              - crm.objects.contacts.write
        provider:
          hubspot:
            authorization-uri: https://app.hubspot.com/oauth/authorize
            token-uri: https://api.hubapi.com/oauth/v1/token
  kafka:
#    bootstrap-servers: localhost:9092 # running with java
    bootstrap-servers: kafka:29092 # use this when running inside docker
    producer:
      retries: 3
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      batch-size: 16384
      buffer-memory: 33554432
      acks: all
    consumer:
      group-id: hubspot-integration-api-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
    topics:
      hubspotWebhookProcessor: hubspot-integration-api.hubspot.webhook.processor

  devtools:
    restart:
      enabled: true

rest-client:
  hubspot:
    apiUrl: https://api.hubapi.com
    contactsResource: /crm/v3/objects/contacts

management:
  endpoints:
    web:
      exposure.include: '*'

resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      waitDurationInOpenState: 24h
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
      recordExceptions:
        - java.io.IOException
  instances:
    HubSpotRestClient:
      baseConfig: default