spring:
  security:
    oauth2:
      client:
        registration:
          hubspot:
            client-id: CLIENT_ID
            client-secret: CLIENT_ID
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/oauth/callback"
            scope:
              - crm.objects.contacts.read
              - crm.objects.contacts.write
        provider:
          hubspot:
            authorization-uri: https://app.hubspot.com/oauth/authorize
            token-uri: https://api.hubapi.com/oauth/v1/token

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html